### ISSUE TITLE
Cannot add files to Information Module

### ISSUE THREAD

**Issue by JackDMF** [JWManagement/JWManagement#432]
When you try to upload a new file, the server responds with a 503 error (seen in the developer tools only).

1. Go to 'Information module'
2. Click on 'Upload'
3. Choose a file (pdf)
4. See error in developer tools - network tab (edge/chrome...)
5. A new box for the file appears with its title, but without a working link (href property is missing - might be because it is empty)

**Expected behavior**
File should be uploaded and be downloadable

**Comment by JackDMF** [comment]
Found a stacktrace:

    Error in method "/cfs/files/:value/:value/", Error: Error: Storage name already exists: "_tempstore"
    at new FS.StorageAdapter (packages/cfs_storage-adapter.js:72:11)
    at new FS.Store.GridFS (packages/cfs:gridfs/gridfs.server.js:46:10)
    at mountStorage (packages/cfs:tempstore/tempStore.js:70:28)
    at EventEmitter.FS.TempStore.createWriteStream (packages/cfs:tempstore/tempStore.js:248:3)
    at Object.httpPutUpdateHandler (packages/cfs_access-point.js:499:46)
    at Object.put (packages/cfs_access-point.js:677:45)
    at packages/cfs_http-methods.js:604:33

**Comment by tim-antkowiak** [comment]
Hey @JackDMF , thanks for the report. Unfortunately the feature of uploading files is not supported anymore. You can use a link to an external source like Dropbox or Google Drive instead. Sorry for the inconveniences.
